### ISSUE TITLE
create error.

### ISSUE THREAD

**Issue by Yinxing-Gao** [mailgun/mailgun-php#673] opened 2020-03-19 22:30 UTC
I just use the mailgun from https://github.com/mailgun/mailgun-php.
I am first for using mailgun this is first comment for me.
I can get create error when sending mail.

my error is " Error: Request failed with status code 500 ".

my code is blow.

```php
function sendMail($to) {
require 'vendor/autoload.php';
use Mailgun\Mailgun;

    $mg = Mailgun::create('KEY');
    $mg->messages()->send('***@aaa.co', [
        'from'  => '***@aaa.co',
        'to'    => $to,
        'subject' => 'The PHP SDK is awesome!',
        'html'  => 'welcome!',
    ]);
    return true;
}
```

What's wrong? Please help. Thanks

**Comment by uavn** [comment] 2020-09-25 15:28
@Yinxing-Gao the issue is in your code:

this **use** and **require_once** shouldn't be used inside a function, you need to move them to the top of your script

```
function sendMail($to) {
require 'vendor/autoload.php';
use Mailgun\Mailgun;
```

the second point is from what I can see, that you are using email ('***@aaa.co') instead of domain as a first argument of the "->send(" method.

**Comment by DavidGarciaCat** [comment] 2020-09-25 17:42
Thanks @uavn for highlighting the issue with the `use` and `require_once` calls, as well as the wrong domain.

Closing this issue now

**Closed by DavidGarciaCat** 2020-09-25 17:42 UTC
