### ISSUE TITLE
Can't send binary attachments through cURL

### ISSUE THREAD

**Issue by michaeldk** [mailgun/mailgun-php#429] opened 2017-12-13 18:35 UTC
Hello,
I've been trying to send mails with PDF or JPG attachments but it fails in the cURL command formatter because [escapeshellarg](http://php.net/manual/en/function.escapeshellarg.php) receives the file binary contents:

Stacktrace:

    Symfony\Component\Debug\Exception\FatalErrorException:
    Error: escapeshellarg(): Input string contains NULL bytes
    at vendor/php-http/message/src/Formatter/CurlCommandFormatter.php:43

CurlCommandFormatter:

    $body = $request->getBody();
    if ($body->getSize() > 0) {
        if (!$body->isSeekable()) {
            return 'Cant format Request as cUrl command if body stream is not seekable.';
        }

        $command .= sprintf(' --data %s', escapeshellarg($body->__toString()));
	    
        $body->rewind();
    }

This is how I initialize the `attachment` parameter:

    $param['attachment'] = array();
    foreach ($attachments as $attachment) {
        $filename = $attachment['fileName'];
        $fileContent = $attachment['content']; // file_get_contents of PDF file made with wkhtmltopdf
        $tmpPath = '/tmp/' .$filename;
        file_put_contents($tmpPath, $fileContent);
            
        array_push($param['attachment'], array(
            'filePath' => $tmpPath,
            'filename' => $filename,
        ));
    }

When the call to `escapeshellarg` is removed, it works as expected and my files are attached.

**Comment by DavidGarciaCat** [comment] 2017-12-14 01:17
Hi,

After a quick look through my phone, I can't see neither a single reference
to Mailgun SDK, looks like everything is related with your own code, that
is not able to do what you want.

If the issue is not related with the SDK code and you don't get a Mailgun
Exception then I think you're looking for support in the wrong place :-)

If this is really related with the SDK, can you please provide the full
piece of code that causes the issue? As I said, looks like the error is not
thrown by a Mailgun SDK call.

Cheers,

**Comment by michaeldk** [comment] 2017-12-14 07:55
Hey,

I do call the Mailgun SDK right after:

    $mg = Mailgun::create($currentProject->getMailgunApikey());
    $response = $mg->messages()->send($currentProject->getMailgunDomain(), $param);

`$param` looks like this:
    
    array { 
        "from" => "Live",
        "to" => "myto@mail.com",
        "subject" => "Confirmation de votre paiement",
        "o:testmode" => "no",
        "html" => "...",
        "text" => "Confirmation de votre paiement",
        "v:mail-data" => {"id":xxx,"key":xxxx}",
        "attachment" => array(2) { 
            [0]=> array(2) { "filePath" => "/tmp/Live_201712140842_863.pdf", "filename" => "Live_201712140842_863.pdf" },
            [1]=> array(2) { "filePath" => "/tmp/Live_201712140842_609.pdf", "filename" => "Live_201712140842_609.pdf" } 
        }
    }



The exception is not thrown by the Mailgun SDK itself but by `vendor/php-http/message/src/Formatter/CurlCommandFormatter` which is called by the Mailgun SDK. The problem being that the file binary contents is outputted in the command line (even if I provide an external link to an image hosted by google for example) and `escapeshellarg` inside php-http/message fails on NULL bytes.

My guess is that I am missing something (I can't be the first one to try and send a PDF file through the Mailgun SDK, right?) but I tried all I could think of. The PDF files are valid; if I try to attach a simple test.txt file with "hello" in there, it works; If I remove the call to `escapeshellarg` in the cURL library, it works too. I think the file binary contents should not be escaped but how can I manage that ?

**Comment by DavidGarciaCat** [comment] 2017-12-14 09:03
Hey @michaeldk

If the exception is thrown by the `php-http/message` vendor then I would say it's not related with the SDK, however I would like to check it myself.

In the meantime, may I suggest to check if you can open the file that you created with this call? `file_put_contents($tmpPath, $fileContent);` - Just want to make sure the file is not corrupted and it can be opened, because if not then the problem won't be - obviously - related with the SDK.

Please let us know if it works.

Cheers,

**Comment by michaeldk** [comment] 2017-12-14 10:32
Hey,

I have tested these files and they are fine. As I said, if I remove the call to escapeshellarg then it works as intended and my PDF files are attached and not corrupted. But as the binary file is outputted as is in the cURL call, escapeshellarg fails because the binary content contains NULL bytes. The problem also occurs with a JPEG file, even if I provide the SDK with its URL and not a local path.

Maybe I missed something while setting up the SDK so that it prevents php-http/message to escape the binary file?

**Comment by michaeldk** [comment] 2018-01-03 10:55
Bump :)

Has anyone else trouble sending binary files through this API?

**Comment by DavidGarciaCat** [comment] 2018-01-03 22:42
Hi @michaeldk 

Sorry, I didn't have time to check it, it has been a hard month at work and needed to take care about several things.

I'll run some tests ASAP and I'll let you know.

Cheers,

**Comment by michaeldk** [comment] 2018-01-16 09:48
Hey @DavidGarciaCat :)

Did you have any time to run some tests?

Thanks!

**Comment by z38** [comment] 2018-01-16 12:10
Hi @michaeldk, I'm sorry we haven't been able to fix this issue so far. I tried to replicate your setup but I wasn't successful so far. Which HTTP client/library did you install along with Mailgun (e.g. `php-http/curl-client`)? Can you share the full stacktrace of when the error occurs?

**Comment by michaeldk** [comment] 2018-01-17 13:16
Hey @z38 :)

I have to admit that I don't know how to find the information. I believe we're using `guzzlehttp/guzzle` v6.3.0, does that make any sense?

**Comment by DavidGarciaCat** [comment] 2018-01-17 14:14
Hi all,

I have tested it and I am unable to replicate the same error. The steps I followed:

```bash
$ mkdir test
$ cd test
$ composer require mailgun/mailgun-php php-http/curl-client guzzlehttp/psr7
```

These are the downloaded vendors:

```
Using version ^2.4 for mailgun/mailgun-php
Using version ^1.7 for php-http/curl-client
Using version ^1.4 for guzzlehttp/psr7
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 14 installs, 0 updates, 0 removals
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing php-http/discovery (1.3.0): Loading from cache
  - Installing symfony/options-resolver (v3.4.3): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing php-http/message-factory (v1.0.2): Loading from cache
  - Installing clue/stream-filter (v1.4.0): Loading from cache
  - Installing php-http/message (1.6.0): Loading from cache
  - Installing php-http/promise (v1.0.0): Loading from cache
  - Installing php-http/httplug (v1.1.0): Loading from cache
  - Installing php-http/client-common (1.7.0): Loading from cache
  - Installing php-http/multipart-stream-builder (1.0.0): Loading from cache
  - Installing mailgun/mailgun-php (v2.4.0): Loading from cache
  - Installing php-http/curl-client (v1.7.0): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
php-http/discovery suggests installing puli/composer-plugin (Sets up Puli which is recommended for Discovery to work. Check http://docs.php-http.org/en/latest/discovery.html for more details.)
php-http/message suggests installing zendframework/zend-diactoros (Used with Diactoros Factories)
php-http/message suggests installing slim/slim (Used with Slim Framework PSR-7 implementation)
php-http/client-common suggests installing php-http/logger-plugin (PSR-3 Logger plugin)
php-http/client-common suggests installing php-http/cache-plugin (PSR-6 Cache plugin)
php-http/client-common suggests installing php-http/stopwatch-plugin (Symfony Stopwatch plugin)
Writing lock file
Generating autoload files
```

Then I added a new `test.php` file with this content:

```php
<?php

require 'vendor/autoload.php';

use Mailgun\Mailgun;

$params = [
    'from'    => 'noreply@domain.com',
    'to'      => 'me@domain.com',
    'subject' => 'MailGun email with attached files',
    'text'    => 'This email contains 2 attached images and 1 PDF file.',
    'attachment' => [
        [
            'filePath' => 'attachment/php.jpg',
            'filename' => 'php.jpg'
        ],
        [
            'filePath' => 'attachment/symfony.png',
            'filename' => 'symfony.png'
        ],
        [
            'filePath' => 'attachment/pdf-file.pdf',
            'filename' => 'pdf-file.pdf'
        ],
    ],
];

$mg = Mailgun::create('key-xxxxxxxx');
$mg->messages()->send('domain.com', $params);
```

And when I ran `php -f test.php` the email was sent as expected. I got it with the same copy and content I set so the whole workflow must be fine. This was delivered on my INBOX:

<img width="591" alt="screen shot 2018-01-17 at 14 09 48" src="https://user-images.githubusercontent.com/7809429/35046851-282eb9ca-fb90-11e7-914b-bf310d9efdce.png">

Unless we get a full stack trace where we can see that Mailgun SDK is related then I must assume the issue is not related with Mailgun.

**Comment by DavidGarciaCat** [comment] 2018-01-17 14:22
INBOX:

<img width="591" alt="screen shot 2018-01-17 at 14 09 48" src="https://user-images.githubusercontent.com/7809429/35047392-ae55ec52-fb91-11e7-83c3-b2bf23675371.png">

`attachment/php.jpg`

![php](https://user-images.githubusercontent.com/7809429/35047428-c7945fa0-fb91-11e7-8661-77ce1d33d9fa.jpg)

`attachment/symfony.png`

![symfony](https://user-images.githubusercontent.com/7809429/35047433-cbff84a2-fb91-11e7-9681-2d0797ce5f39.png)

`attachment/pdf-file.pdf`

[pdf-file.pdf](https://github.com/mailgun/mailgun-php/files/1639284/pdf-file.pdf)

**Comment by DavidGarciaCat** [comment] 2018-01-17 14:23
https://gist.github.com/DavidGarciaCat/acbf2141b62bdd3bfe3ddff8cafe31e9

**Comment by michaeldk** [comment] 2018-01-17 17:06
Many thanks @DavidGarciaCat !

I tested your scripts with both php-http/curl-client & php-http/guzzle6-adapter (which I believe is the one used in my case) and it works fine.

I'll keep looking and update this as I go.

**Comment by DavidGarciaCat** [comment] 2018-01-17 20:02
Hey @michaeldk 

Please note I am just following the steps to install the SDK:
https://github.com/mailgun/mailgun-php/blob/master/README.md#installation

Given I have just checked the process, it works and just got your confirmation, I am going to close this issue.

Cheers,

**Closed by DavidGarciaCat** 2018-01-17 20:02 UTC

**Comment by michaeldk** [comment] 2018-01-22 08:16
Hello,

The problem seems to come from the fact that this SDK prepares a cURL command that is not working with any HttpClient using `Http\Message\Formatter\CurlCommandFormatter` to format cURL requests. 
When using the HttplugBundle for SF, it provides a decorator `Http\HttplugBundle\Collector\ProfileClient` using the aforementioned formatter which fails on NULL bytes (because of [`escapeshellarg`](http://php.net/manual/fr/function.escapeshellarg.php)).

When searching online, it seems that files should be passed by path and not printed as-if on the command line to avoid this issue.

Do you have any idea how I could make the Mailgun SDK's requests pass this formatter?

**Comment by DavidGarciaCat** [comment] 2018-01-22 10:14
Hey @Nyholm 

I think that you are/were related with HTTP [HttplugBundle](https://github.com/php-http/HttplugBundle) so I was wondering if you have any idea about this.

Cheers,

**Comment by z38** [comment] 2018-01-22 10:16
@michaeldk Thank you for your insights! I wondered how the `CurlCommandFormatter` got pulled into this. I reported the issue in php-http/message#91.

**Comment by michaeldk** [comment] 2018-03-05 14:26
If anyone comes here and had the same issue, I managed to solve it by disabling profiling in the [httplugbundle configuration](http://docs.php-http.org/en/latest/integrations/symfony-full-configuration.html) which prevents the ProfileClient to be used and thus prevents the CurlCommandFormatter to be called.

**Comment by bsadnu** [comment] 2018-08-09 17:25
@michaeldk , I've got the same problem. Disabling profiling really helped. Thanks for saving a lot of my time.

**Comment by Nyholm** [comment] 2018-08-09 18:06
This issue is fixed here: https://github.com/php-http/message/pull/94

A new version of that library will be tagged shortly.
