### ISSUE TITLE
Batch send different text/html per mail

### ISSUE THREAD

**Issue by sandrodz** [mailgun/mailgun-php#671] opened 2020-03-09 08:17 UTC
I was looking at the batch sending docs, but could not find relevant info.
Is there a way to batch send different html content per mail?

I would like to use batch sending capabilities, but each email content is slightly different.

**Comment by kymodoke** [comment] 2020-03-12 12:33
Yeas, I do that by using recipient variables in the templates (both text and html).

For instance:
`Hello %recipient.first% %recipient.last%, 

Here is the link for your evaluation form: https://www.example.com/submit-evaluation/?ref=%recipient.linkid%`

**Comment by sandrodz** [comment] 2020-03-15 06:56
> Yes, I do that by using recipient variables in the templates (both text and html).
> 
> For instance:
> 
> ```
> Hello %recipient.first% %recipient.last%, 
> 
> Here is the link for your evaluation form: https://www.example.com/submit-evaluation/?ref=%recipient.linkid%
> ```

And how do you pass data to those template variables?

**Comment by kymodoke** [comment] 2020-03-15 10:01
Pass it in the recipient array.
Have you read the doc ? https://github.com/mailgun/mailgun-php/blob/master/src/Message/README.md

$batchMessage->addToRecipient("john.doe@example.com", **array("first" => "John", "last" => "Doe")**);
`

**Comment by DavidGarciaCat** [comment] 2020-09-25 18:01
Due to there are no new messages after the last example sent by @kymodoke, I assume the problem is now solved, so I am closing this issue.

If this is not the case, please send a full piece of code with the logic and the error message, and we can open the issue again.

**Closed by DavidGarciaCat** 2020-09-25 18:01 UTC

**Comment by ashirafumiiro** [comment] 2023-04-18 10:26
> > Yes, I do that by using recipient variables in the templates (both text and html).
> > For instance:
> > ```
> > Hello %recipient.first% %recipient.last%, 
> > 
> > Here is the link for your evaluation form: https://www.example.com/submit-evaluation/?ref=%recipient.linkid%
> > ```
> 
> And how do you pass data to those template variables?

How to I get %recipient.**% to work in templates stored by mailgun templates api?
Thank you!

**Comment by ashirafumiiro** [comment] 2023-04-18 10:27
> Yes, I do that by using recipient variables in the templates (both text and html).
> 
> For instance:
> 
> ```
> Hello %recipient.first% %recipient.last%, 
> 
> Here is the link for your evaluation form: https://www.example.com/submit-evaluation/?ref=%recipient.linkid%
> ```

How to I get %recipient.**% to work in templates stored by mailgun templates api?
Thank you!
