### ISSUE TITLE
Batch sending with more than 1000 recipients

### ISSUE THREAD

**Issue by csimpi** [mailgun/mailgun-php#469] opened 2018-07-13 22:29 UTC
Hi guys, I don't find the info the documentation about what will happen If I provide 20 000 (more than 1000) recipient's data. 
Will it split the request to 20 x 1000 recipients and send the message automatically to each recipient or after the 1000 recipient it will drop the request and the email won't be sent after the 1000 recipients?
I'm not sure If I need to handle this in the code, or `mailgun-php` lib will able to handle it.

thx,
Peter

**Comment by DavidGarciaCat** [comment] 2018-07-14 00:07
Hello @csimpi 

As far as I am aware of, latest (already implemented) updates on this SDK are not going to split your list of recipients and then send your message through multiple requests to Mailgun's API on behalf of you, instead if the API returns an error then we will throw a PHP Exception.

Please note this SDK is maintained by OpenSource contributors and collaborators (not by Mailgun Tech Team) so any unexpected change on Mailgun's API could lead to an unexpected behaviour if we implement limitations or extra processes, and the responsibility on that case would rely on us due a wrong decision when developing the SDK.

That's why we can't take decisions on behalf of you, and we expect that you'll keep control of your requests.

Tip: personally, if I know the limit is 1000 recipients, I prefer to send 2 requests of 500 because in this way I am 100% sure that any unexpected change won't cause me a blockder, but this is my decision and it will incur on any API rate limit on my end. So far it worked on my case and never had a blocker.

As per a quick chat with Mailgun's support team, I was told that [these are the limits](https://github.com/mailgun/mailgun-php/issues/461) **for pagination** on GET requests, but I wasn't told about any limit that I should bear in mind for the number of recipients

Hope this helps.

Cheers,

PS: I am going to close this issue due it's more a question than an issue.

**Closed by DavidGarciaCat** 2018-07-14 00:07 UTC

**Comment by csimpi** [comment] 2018-07-14 00:50
Thank you for your answer. In the meantime I made a quick script that handles the sending exactly the same way as you proposed, I split the recipient list (every 500 address is a new chunk) before sending.

I can see the real problem also, the limitation depends on the sender's server's setting, the request sizes can be limited and the successful request depends on the size of the recipient custom values object etc etc ... 

My question is about this part of the mailgun official documentation:

`Note The maximum number of recipients allowed for Batch Sending is 1,000.`

`Note Recipient variables should be set as a valid JSON-encoded dictionary, where key is a plain recipient address and value is a dictionary with variables.`
source: https://documentation.mailgun.com/en/latest/user_manual.html#batch-sending

Below my quick solution that chucks the recipients to pieces (every chuck has 500 recipients). 
Any suggestions are welcome 🌷 

```
        $chunks = array_chunk($data['recipient-variables'],500,true);
        $result = [];
        foreach ($chunks as $chunk){
            # Make the call to the client.

            $result[] = $mgClient->sendMessage($domain, array(
                'from'    => $form,
                'to'      => array_keys($chunk),
                'subject' => $data['subject'],
                'html'    => $html,
                'recipient-variables' => json_encode($chunk),
                'o:tracking' => true,
                //'o:testmode' => true
            ));
        }
```

Example value for `$data['recipient-variables']` array

```
$data['recipient-variables'] = [
      'recipient1@email.com' => ['fisrt_name'=>'John','last_name'=>'Doe'],
      'otherrecipient@hotmail.com' => ['fisrt_name'=>'Clara','last_name'=>'Stevenson']
];
```

**Comment by DavidGarciaCat** [comment] 2018-07-14 02:08
Hi @csimpi 

On a first instance, please allow me to suggest the new call to send messages - the code that you're using looks like the one that will be removed once we release v3

https://github.com/mailgun/mailgun-php#usage
```php
$mg->messages()->send('example.com', [
  'from'    => 'bob@example.com',
  'to'      => 'sally@example.com',
  'subject' => 'The PHP SDK is awesome!',
  'text'    => 'It is so simple to send a message.'
]);
```

Having said that, I can see your point with a single Message ID instead of the 500 that you're expecting, maybe for this case we can open a new issue and look for a potential / suitable solution.

If you're feeling comportable, Pull Requests are welcomed. 😄

**Comment by csimpi** [comment] 2018-07-15 06:35
Thank you for your suggestion, I followed the official PHP documentation on the mailgun website, thank you for the heads up, I'm going to upgrade my code, thank you!
