### ISSUE TITLE
How to set Reply To address?

### ISSUE THREAD

**Issue by MACscr** [mailgun/mailgun-php#355] opened 2017-05-18 21:14 UTC
I'm sending an email like so, but haven't really figured out the 'reply-to' part yet as it does not appear to get sent. I'm using mailgun to send lead form results to our office manager and I want them to be able to reply directly to the email address the user entered in the form.

```
    # First, instantiate the SDK with your API credentials
    $mg = Mailgun::create($api_key);

    # Now, compose and send your message.
    $response = $mg->messages()->send('examle.com', [
      'from'    => 'conversions@mg.example.com',
      'reply-to'=> $form_data['email'],
      'to'      => $email_to,
      'subject' => $email_subject,
      'text'    => 'It is so simple to send a message.'
    ]);
```

**Comment by DavidGarciaCat** [comment] 2017-05-18 22:27
Hi @MACscr

Based on official Mailgun API docs here https://documentation.mailgun.com/api-sending.html#sending you can specify the `Reply-to` option, but it must be defined as `h:X-My-Header`:

<img width="833" alt="screen shot 2017-05-18 at 23 24 40" src="https://cloud.githubusercontent.com/assets/7809429/26225880/48e36c44-3c21-11e7-9766-49dfb564db86.png">

Please confirm if this is working on your case, and keep us posted. If the new parameter works then feel free to close the issue.

Cheers,

**Comment by MACscr** [comment] 2017-05-18 23:16
That did it. Thanks!

**Comment by DavidGarciaCat** [comment] 2017-05-19 00:10
If the issue is now resolved, please feel free to close it. Cheers,

**Closed** 2017-05-19 05:47 UTC

**Comment by tuzmusic** [comment] 2019-08-05 23:25
I am having trouble with this, I'm trying to construct the request in postman, and I've tried putting `Reply-To` as a header key and an email as the value (see code below), and I've also tried without that header but with a param with the key `h:Reply-To` but when I hit "reply" to the email that gets send, it always replies to the sender instead of my reply-to address. 

Can anyone help me? 
```
POST /v3/sandboxXXXXba.mailgun.org/messages?from=messages@xxxx.com&amp; to=xxxx1@gmail.com&amp; subject=hello&amp; text=mailgun-test HTTP/1.1
Host: api.mailgun.net
Reply-To: xxxx2@gmail.com
Authorization: Basic xxxx
cache-control: no-cache
Postman-Token: xxxxx
```

**Comment by DavidGarciaCat** [comment] 2019-08-06 21:34
Hey, @tuzmusic 

Postman is not this SDK, so that Postman support is not supported here :smiley: 

Please refer to:
- [My previous comment](https://github.com/mailgun/mailgun-php/issues/355#issuecomment-302574463) on this issue, posted in 2017 (parameter, not header)
- The official Mailgun's [API docs](https://documentation.mailgun.com/en/latest/api-sending.html#sending) (under Parameters, not header)

The `Reply To` is not a header but a parameter of the HTTP Post request, so that you shouldn't pass it as one of the HTTP Headers when sending the request.

Please take a look to the examples included as part of the API docs for further details, and please note that the parameters are not sent as part of the query string (`?...`) or as headers (`-H "..."`):

https://documentation.mailgun.com/en/latest/api-sending.html#examples

Hope this helps,

----

Locking this conversation due to the issue that was reported in 2017 got confirmation that worked, and there's no need to spam other GitHub users.
