### ISSUE TITLE
Puli Factory is not available

### ISSUE THREAD

**Issue by temuri416** [mailgun/mailgun-php#716] opened 2020-10-31 19:35 UTC
Following to the letter installation steps from https://github.com/mailgun/mailgun-php#installation results in 'Puli Factory is not available' exception being thrown.

**Comment by uavn** [comment] 2020-11-06 18:49
@temuri416 see https://github.com/mailgun/mailgun-php/issues/646

**Comment by DavidGarciaCat** [comment] 2020-11-16 17:28
This seems to duplicate another issue.

I am also unable to reproduce the error, as you can see on the message I posted here just a few minutes ago:

https://github.com/mailgun/mailgun-php/issues/665#issuecomment-728198848

Please let's keep just one thread for the same error, as creating many issues makes it hard for tracking purposes.

**Comment by nikiviro** [comment] 2020-12-03 14:17
I have also came across this issue. This exception is thrown by 3rd party library - HTTPlug Discovery that Mailgun is using. 

That exception is catched and logged in HTTPlug Discovery, so it is not really a problem and it is expectet behaviour that you should not worry about. [https://github.com/php-http/discovery/issues/152  ](url)

You just need to configure your system to not track exceptions in 3rd party libraries that do not bubble up to your application.

**Comment by DavidGarciaCat** [comment] 2020-12-09 13:32
I don't remember seeing that error after following the steps I described on the attached link (comment above). Anyway, I understand the issue can be considered as solved, so I'm closing it.

**Closed by DavidGarciaCat** 2020-12-09 13:32 UTC
