### ISSUE TITLE
Your credentials are incorrect

### ISSUE THREAD

**Issue by billyanto** [mailgun/mailgun-php#454] opened 2018-04-06 08:17 UTC
i have problem when load this code ten mb browser give me error like this "Your credentials are incorrect"

this is my code
```

use Mailgun\Mailgun;
require '../vendor/autoload.php';

$mg = Mailgun::create('key-xxx');

$mg->messages()->send('sandboxxxx.mailgun.org', [
  'from'    => 'h@gmail.com',
  'to'      => 'hb@gmail.com',
  'subject' => 'The PHP SDK is awesome!',
  'text'    => 'It is so simple to send a message.'
]);
```

**Comment by Nyholm** [comment] 2018-04-06 09:02
I cannot tell you anything else but "It seams like your credentials are incorrect."

**Comment by DavidGarciaCat** [comment] 2018-04-06 09:03
If the error message says `Your credentials are incorrect` then looks like the problem is related with your API Key or the domain, probably. Please review your credentials and domain, and try again. If the problem is not solved, would be useful to get more details.

**Comment by nox7** [comment] 2018-05-09 22:29
I can confirm I am running similar code in PHP with a verified API key and receiving the same error. What more information can I provide? I back-traced the stack and it appears it's not related to the PHP library.

**Comment by DavidGarciaCat** [comment] 2018-05-09 22:37
Hi @nox7 

I would say to make sure both the API Key and the domain have no typos or blank spaces before/after, maybe escape them with the `trim()` function. If the problem is not solved with this, maybe the full stack trace might help to find out what's going on.

Also, maybe would be useful to know the operating system that you're using as well as if you have installed PHP through an all-in-one software tool or if you have compiled it manually, etcetera. It might be a problem related with your environment, not with the source code - although the `Your credentials are incorrect` looks like it's an API response...

Cheers,

**Comment by nox7** [comment] 2018-05-09 22:39
@DavidGarciaCat 

Hey thanks for the quick reply, I was doing a stack trace as you mentioned this. Could I have some clarification, to speed things up, where the API key is packaged for the request? I have outputted the request headers and the POST data but neither has my API key in it? This seems like the issue if I have tracked it correctly.

**Comment by DavidGarciaCat** [comment] 2018-05-09 22:49
Hi @nox7 

When you create the Mailgun Client then we need to pass the API Key, that is passing it to the `HttpClientConfigurator` object, as you can see on the named constructor:

https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Mailgun.php#L110-L115

Then the API Key is pre-set when the client is configured:

https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/HttpClientConfigurator.php#L68-L84

Does it help?

**Comment by DavidGarciaCat** [comment] 2018-05-09 22:51
Following up my previous comment, the named constructor calls the parent constructor, that sets up the configuration: 

https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Mailgun.php#L95-L103

```php
    public static function configure(
        HttpClientConfigurator $configurator,
        Hydrator $hydrator = null,
        RequestBuilder $requestBuilder = null
    ) {
        // THIS LINE PREPARES THE CONFIGURATION FOR THE CLIENT,
        // INCLUDING THE API KEY
        $httpClient = $configurator->createConfiguredClient();

        return new self($configurator->getApiKey(), $httpClient, 'api.mailgun.net', $hydrator, $requestBuilder);
    }
```

**Comment by nox7** [comment] 2018-05-10 00:11
@DavidGarciaCat 

Outputting the full request from Guzzle provides me with the following content in the screenshot link:

https://i.imgur.com/6qPNuzc.png

It may be me outputting in the wrong location before the API key is added, but seems to be the request is created and then sent without the API key.

I am outputting from \php-http\message\src\MessageFactory\GuzzleMessageFactory.php

Which I believe to be the last stop before Guzzle handles the actual request stream, and I am under the assumption the correct headers should exist by then.

**Comment by DavidGarciaCat** [comment] 2018-05-10 01:18
Hi @nox7 

I just ran a test with that repo, and keeping your API Key and domain I got the same error:

```
POST/v3/mail.animeandmangaclub.net/messages
Fatal error: Uncaught Mailgun\Exception\HttpClientException: Your credentials are incorrect. in .../vendor/mailgun/mailgun-php/src/Mailgun/Exception/HttpClientException.php:63
Stack trace:
#0 .../vendor/mailgun/mailgun-php/src/Mailgun/Api/HttpApi.php(93): Mailgun\Exception\HttpClientException::unauthorized(Object(GuzzleHttp\Psr7\Response))
#1 .../vendor/mailgun/mailgun-php/src/Mailgun/Api/HttpApi.php(73): Mailgun\Api\HttpApi->handleErrors(Object(GuzzleHttp\Psr7\Response))
#2 .../vendor/mailgun/mailgun-php/src/Mailgun/Api/Message.php(52): Mailgun\Api\HttpApi->hydrateResponse(Object(GuzzleHttp\Psr7\Response), 'Mailgun\\Model\\M...')
#3 .../sendMessage.php(10): Mailgun\Api\Message->send('mail.animeandma...', Array)
#4 {main}
  thrown in .../vendor/mailgun/mailgun-php/src/Mailgun/Exception/HttpClientException.php on line 63
```

However, when I switched to one of my domains and my API Key it worked, so looks like your account is not valid or your APY Key / Domain are invalid.

![capture 2018-05-04 at 2 10 35](https://user-images.githubusercontent.com/7809429/39847135-c97a2426-53f7-11e8-957e-7f40826be74d.png)

Please make sure that:
- Your API Key is matching
- Your Domain is matching (if you registered `domain.com` then use `domain.com` instead of a subdomain)
- Your account has been unlocked, providing the card details (if you don't reach 10k emails then you won't be charged)

If the problem is not fixed with this review then:
- Try to regenerate your API Key
- If that doesn't fix the problem, you will need to raise a Support ticket with Mailgun so they can review your account.

Based on the fact that the test worked once I replaced the API Key and Domain, I must assume this issue is not related with the SDK, instead is related with your account's status or your domain/key.

I am going to close this issue now, but if you make it working after reload the Key, review the domain and - if needed - reaching Mailgun support, please let us know so any other potential developer could find out what you did.

Enjoy the rest of your day (and good night for me)

**Closed by DavidGarciaCat** 2018-05-10 01:18 UTC

**Comment by nox7** [comment] 2018-05-10 11:29
The issue was that I was under an incorrect assumption about the whitelisting feature. I whitelisted my **server IP that I was using the SDK from**, but this was causing the incorrect credentials error. I was simply incorrect in whitelisting my server IP. To anyone having this issue, try debugging without a whitelist of IPs.

**Comment by DavidGarciaCat** [comment] 2018-05-11 16:54
@nox7 you're welcome! enjoy your weekend!

**Comment by matteocollina** [comment] 2018-06-12 06:50
@nox7 you are right! Just removed the ip from whitelist and it works

**Comment by MisterDuval** [comment] 2018-09-11 08:44
Same problem here, thanks ;-)

**Comment by Vohidjon** [comment] 2019-04-17 10:50
@nox7 Had the same problem. Thank you :)
