### ISSUE TITLE
Filtering Events by message-id returns an empty array

### ISSUE THREAD

**Issue by matteo-tech** [mailgun/mailgun-php#737] opened 2021-01-11 14:23 UTC
My PHP Code:
```
require '../system/classes/mailgun-sdk/vendor/autoload.php';
use Mailgun\Mailgun;

$mg = Mailgun::create('api-key', 'https://api.eu.mailgun.net'); // For EU servers
$domain      = 'mg.exemple.com';
$messageId = '20210111133822.1.DF11FB202661516A@exemple.com';

$queryString = array(
    'message-id' => $messageId,
);

$result = $mg->events()->get($domain, $queryString);

print_r($result);
```
Result:
```
Mailgun\Model\Event\EventResponse Object
(
    [items:Mailgun\Model\Event\EventResponse:private] => Array
        (
        )

    [paging:Mailgun\Model\Event\EventResponse:private] => Array
        (
            [previous] => https://api.eu.mailgun.net/v3/exemple.com/events/WzM...
            [first] => https://api.eu.mailgun.net/v3/exemple.com/events/WzM...
            [last] => https://api.eu.mailgun.net/v3/exemple.com/events/WzMs...
            [next] => https://api.eu.mailgun.net/v3/exemple.com/events/WzMse....
        )

)
```

I noticed that the message-id value is encoded twice the first time with the http_build_query function and a second time by one of the http libraries

1° encode -> 20210111133822.1.DF11FB202661516A%40exemple.com
2° encode -> 20210111133822.1.DF11FB202661516A%2540exemple.com

Test:

```
Phalcon\Http\Message\Request Object
(
    [body:protected] => Phalcon\Http\Message\Stream Object
        (
            [handle:protected] => Resource id #10
            [stream:protected] => Resource id #10
        )

    [headers:protected] => Phalcon\Collection Object
        (
            [data:protected] => Array
                (
                )

            [insensitive:protected] => 1
            [lowerKeys:protected] => Array
                (
                )

        )

    [protocolVersion:protected] => 1.1
    [method:protected] => GET
    [requestTarget:protected] => 
    [uri:protected] => Phalcon\Http\Message\Uri Object
        (
            [fragment:Phalcon\Http\Message\Uri:private] => 
            [host:Phalcon\Http\Message\Uri:private] => 
            [pass:Phalcon\Http\Message\Uri:private] => 
            [path:Phalcon\Http\Message\Uri:private] => /v3/exemple.com/events
            [port:Phalcon\Http\Message\Uri:private] => 
            [query:Phalcon\Http\Message\Uri:private] => message-id=20210111133822.1.DF11FB202661516A%2540exemple.com
            [scheme:Phalcon\Http\Message\Uri:private] => 
            [user:Phalcon\Http\Message\Uri:private] => 
        )

)
Mailgun\Model\Event\EventResponse Object
(
    [items:Mailgun\Model\Event\EventResponse:private] => Array
        (
        )

    [paging:Mailgun\Model\Event\EventResponse:private] => Array
        (
            [previous] => https://api.eu.mailgun.net/v3/exemple.com/events/WzMs.....
            [first] => https://api.eu.mailgun.net/v3/exemple.com/events/WzMs.....
            [last] => https://api.eu.mailgun.net/v3/exemple.com/events/Wz....
            [next] => https://api.eu.mailgun.net/v3/exemple.com/events/WzMs.....
        )

)
```

**Comment by DavidGarciaCat** [comment] 2021-01-12 08:41
Hi @matteo-tech 

Can you please confirm browsing your Mailgun App website that this ID has one or more events?

If the encoding (or double encoding) is the issue, then we will need to work on a fix. However, we will need to know if this 2nd encoding is caused by a specific HttPlug adapter or if it happens always as it might be triggered by another dependency. If you can bring any additional detail or file path then it might expedite the fix.

Cheers,

**Comment by DavidGarciaCat** [comment] 2021-01-12 08:42
By the way, you are more than welcome if you want to send a pull request (with the updated phpunit tests too) to solve the problem faster.

**Comment by matteo-tech** [comment] 2021-01-12 13:53
I tried to modify this https://github.com/mailgun/mailgun-php/blob/a084abdb8601c0380b668651c169e0560fb435d0/src/Api/HttpApi.php#L114:L129 like this and it seems to work:
```
    protected function httpGet(string $path, array $parameters = [], array $requestHeaders = []): ResponseInterface
    {

        $uri = new Uri($path);
        $uri_new = $uri->withQuery(http_build_query($parameters));

        $request_temp = $this->requestBuilder->create('GET', $path, $requestHeaders);
        $request = $request_temp->withUri($uri_new);
        print_r($request);

        try {
            $response = $this->httpClient->sendRequest(
                $request
            );
        } catch (Psr18\NetworkExceptionInterface $e) {
            throw HttpServerException::networkError($e);
        }

        return $response;
		
    }
```

**Comment by DavidGarciaCat** [comment] 2021-01-12 13:57
Thanks for the feedback. We can try to keep an eye on this update and, once confirmed, apply the fix.

Alternatively, if yourself or another community member can invest some time on reviewing this case and send a PR including the unit tests, then it might definitively expedite the time to fix it.

Cheers,

**Comment by uavn** [comment] 2021-02-17 16:35
^ this can help, and should work for any Request library

**Comment by uavn** [comment] 2021-04-30 19:52
is this still an issue? @matteo-tech @DavidGarciaCat

**Comment by DavidGarciaCat** [comment] 2021-04-30 20:12
I didn't test it after merging the latest update and the merged PR (https://github.com/mailgun/mailgun-php/pull/747), so if anyone can give it a try and post here the feedback, that would be great.

**Comment by Pavlico** [comment] 2021-08-16 12:08
@DavidGarciaCat changes provided with #747 ended up creating #765 , moving back changes from that commit i noticed that there is no double encoding and getting message by its id is working fine. 
Do you still have this issue @matteo-tech Am i missing something while testing ?

**Comment by Pavlico** [comment] 2021-09-15 07:46
Closing since no answer and issue is fixed

**Closed by Pavlico** 2021-09-15 07:46 UTC
