### ISSUE TITLE
Mail stopped sending

### ISSUE THREAD

**Issue by chumylee** [mailgun/mailgun-php#443] opened 2018-02-01 15:34 UTC
After a successful implementation of the api the mails were going through and stopped all of a sudden, with the following error message 

 Fatal error: Maximum execution time of 30 seconds exceeded in ..\mailgun\vendor\guzzle\guzzle\src\Guzzle\Http\Curl\CurlMulti.php on line 241

What might be the cause of this

**Comment by DavidGarciaCat** [comment] 2018-02-01 22:36
Hi @chumylee 

The error is thrown by Guzzle, not by Mailgun.

Please browse Google with the error message:
https://www.google.co.uk/search?q=guzzle+Fatal+error%3A+Maximum+execution+time+of+30+seconds+exceeded

Some suggestions on Guzzle suggests to change some settings on your `php.ini`:
https://github.com/guzzle/guzzle/issues/971

If the error appeared suddenly then I might suggest:
• A potential network issue, check your firewall and run some tests from your shell
• A temporary downtime (if that was the case then I guess you could find tweets about it on Twitter)

Closing this issue due the problem is not related - apparently - with the SDK source code.

Cheers,

**Closed by DavidGarciaCat** 2018-02-01 22:36 UTC

**Comment by chumylee** [comment] 2018-02-02 09:08
Hi @DavidGarciaCat ,

I implemented your suggestion (increased execution time) and no longer get the error message but the emails doesn't go through. 

Cheers
