### ISSUE TITLE
Mailgun result retrieving issue

### ISSUE THREAD

**Issue by Akshay090493** [mailgun/mailgun-php#761] opened 2021-05-17 17:41 UTC
Fatal error: Uncaught Error: Cannot use object of type Mailgun\Model\Event\EventResponse as array in C:\wamp64\www\mailgun\mailgun-php-master\check-mail.php on line 45

I want to print result in in echo for below menton code:

$result = $mgClient->events()->get($domain, $queryString);

**Comment by DavidGarciaCat** [comment] 2021-05-17 18:19
Without a proper debug backtrace, it's hard to know what's going on 😄

**Comment by Akshay090493** [comment] 2021-05-17 18:36
actually, I am trying to get the logs through mailgun API, it is giving me a private array as below, and I want it to print it in notmal formal. is it helpful?
object(Mailgun\Model\Event\EventResponse)[34]
  private 'items' => 
    array (size=4)
      0 => 
        object(Mailgun\Model\Event\Event)[32]
          private 'event' => string 'accepted' (length=8)
          private 'id' => string 'yMVh1T0OSeaQebz3VtLzIg' (length=22)
          private 'timestamp' => int 1621265231
          private 'eventDate' => 
            object(DateTimeImmutable)[31]
              ...
          private 'tags' => 
            array (size=0)
              ...
          private 'url' => string '' (length=0)
          private 'severity' => string '' (length=0)
          private 'envelope' => 
            array (size=3)
              ...
          private 'deliveryStatus' => 
            array (size=0)
              ...
          private 'campaigns' => 
            array (size=0)
              ...
          private 'ip' => string '' (length=0)
          private 'clientInfo' => 
            array (size=0)
              ...
          private 'reason' => string '' (length=0)
          private 'userVariables' => 
            array (size=0)
              ...
          private 'flags' => 
            array (size=2)
              ...
          private 'routes' => 
            array (size=0)
              ...
          private 'message' => 
            array (size=2)
              ...
          private 'recipient' => string 'asavalekar@kingstechmedia.com' (length=29)
          private 'geolocation' => 
            array (size=0)
              ...
          private 'storage' => 
            array (size=2)
              ...
          private 'method' => string 'SMTP' (length=4)
          private 'logLevel' => string 'info' (length=4)
      1 => 
        object(Mailgun\Model\Event\Event)[29]
          private 'event' => string 'delivered' (length=9)
          private 'id' => string 'sEJ8i6-AQYmYfh9YihZuDA' (length=22)
          private 'timestamp' => int 1621265250
          private 'eventDate' => 
            object(DateTimeImmutable)[27]
              ...
          private 'tags' => 
            array (size=0)
              ...
          private 'url' => string '' (length=0)
          private 'severity' => string '' (length=0)
          private 'envelope' => 
            array (size=4)
              ...
          private 'deliveryStatus' => 
            array (size=9)
              ...
          private 'campaigns' => 
            array (size=0)
              ...
          private 'ip' => string '' (length=0)
          private 'clientInfo' => 
            array (size=0)
              ...
          private 'reason' => string '' (length=0)
          private 'userVariables' => 
            array (size=0)
              ...
          private 'flags' => 
            array (size=4)
              ...
          private 'routes' => 
            array (size=0)
              ...
          private 'message' => 
            array (size=3)
              ...
          private 'recipient' => string 'asavalekar@kingstechmedia.com' (length=29)
          private 'geolocation' => 
            array (size=0)
              ...
          private 'storage' => 
            array (size=2)
              ...
          private 'method' => string '' (length=0)
          private 'logLevel' => string 'info' (length=4)

**Comment by DavidGarciaCat** [comment] 2021-05-17 21:46
Well, you have just pasted a Response, which means the API call worked. The problem is that, as an object/array, you cannot use just `echo` unless you reach the item you want to print.

I would encourage something like `echo $response->...` for the object response (the default one).

You can also consider using the `Array Hydrator` if you don't want to use objects, which means you can loop the response until you reach the position you want:

Please follow the examples here: https://github.com/mailgun/mailgun-php#all-usage-examples

I believe this is more a question than an actual error, so I am closing this issue. We can keep commenting if needed.

**Closed by DavidGarciaCat** 2021-05-17 21:46 UTC

**Comment by Akshay090493** [comment] 2021-05-17 22:37
Thank you, David, I got some responses through the example you provided.
But the issue is different than you suggested

below is the code for extracting the result through API.

require 'vendor/autoload.php';
use Mailgun\Mailgun;

# Instantiate the client.
$mgClient    = Mailgun::create('key', 'https://api.mailgun.net');
$domain      = 'biztechradar.com';
$queryString = array(
    'begin'        => 'Mon, 17 May 2021 09:00:00 -0000',
    'ascending'    => 'yes',
    'limit'        =>  25,
    'pretty'       => 'yes',
    'recipient'    => 'test@email.com'
);

# Issue the call to the client.
$result = $mgClient->events()->get($domain, $queryString);

How can I use "Array Hydrator" in this?

I am really sorry to bother you a lot.

**Comment by DavidGarciaCat** [comment] 2021-05-17 23:35
Just instantiate the `ArrayHydrator` as described in the `README` example:

```php
use Mailgun\Hydrator\ArrayHydrator;

$configurator = new HttpClientConfigurator();
$configurator->setApiKey('key-example');

$mg = new Mailgun($configurator, new ArrayHydrator());
```

The next time you run a call, your `$response` variable will be set with an array instead of an object.

**Comment by Akshay090493** [comment] 2021-05-18 12:44
Thank you so much, David, I appreciate the help. your suggestion worked. 
Stay safe. TC
