### ISSUE TITLE
Fatal error: Uncaught Buzz\Exception\NetworkException

### ISSUE THREAD

**Issue by wujekbogdan** [mailgun/mailgun-php#601] opened 2019-05-24 19:00 UTC
I'm getting the following error when calling `$mailgun->messages()->send()`

```
Fatal error: Uncaught Buzz\Exception\NetworkException: file_get_contents(https://api.mailgun.net/v3/sandbox2bb81089713b4a89a1a078510eceba56.mailgun.org/messages): failed to open stream: operation failed in /opt/http/my-app/vendor/kriswallsmith/buzz/lib/Client/FileGetContents.php:27
Stack trace:
#0 /opt/http/my-app/vendor/php-http/client-common/src/HttpClientDecorator.php(28): Buzz\Client\FileGetContents->sendRequest(Object(Nyholm\Psr7\Request))
#1 /opt/http/my-app/vendor/php-http/client-common/src/PluginClient.php(82): Http\Client\Common\EmulatedHttpAsyncClient->sendRequest(Object(Nyholm\Psr7\Request))
#2 /opt/http/my-app/vendor/php-http/client-common/src/Plugin/HistoryPlugin.php(39): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(Nyholm\Psr7\Request))
in /opt/http/my-app/vendor/kriswallsmith/buzz/lib/Client/FileGetContents.php on line 27
```

I'm running the same app on 2 hosts: my development localhost and my remote staging server. Both hosts are running PHP 7.2.x.

The problem happens only on the remote host. I thought that it might be caused by `allow_url_fopen` settings, but it's not the case because this setting is set to enabled on both hosts.

---
"mailgun/mailgun-php": "^2.8",

**Comment by DavidGarciaCat** [comment] 2019-05-25 17:49
Hi @wujekbogdan 

This error is thrown by the HTTP Client (in this case, Buzz) but not the Maiulgun SDK.

The fact that works on local but not on the remote host means that you probably have a missed dependency on the remote host (make sure to run composer, do not copy/paste your local code) or maybe that a blocker (not related to the source code) prevents the communication between your source code and the Mailgun API (like a Firewall rule).

To me, this doesn't look like an error related to the SDK or the HTTP Client itself: the same settings should work on both cases (local and remote) but given it just happens on one of your environments then we must believe that the problem is not even part of any source code but to the remote host that can't connect to the API (so we get a NetworkException).

May I suggest to reach the system administrator that manages the remote server and confirm that:
- Composer is available so you can run it through a deployment process (not an FTP)
- The PHP 7.2 has all the dependencies to make sure the client works
- There are no Firewall rules that can affect your comms between the source code and the API

I am going to close this issue now.

Cheers,

**Closed by DavidGarciaCat** 2019-05-25 17:49 UTC

**Comment by wujekbogdan** [comment] 2019-05-26 08:08
@DavidGarciaCat 

> Composer is available so you can run it through a deployment process (not an FTP)
> The PHP 7.2 has all the dependencies to make sure the client works
> There are no Firewall rules that can affect your comms between the source code and the API

I already did this and also wrote an email to tech support. It might be something on the server.

---

I also use Guzzle HTTP client in my app and it works fine. I see that mailgun-php is already decoupled from HTTP client, so in theory, I should be able to use Guzzle instead of Buzz, but I didn't find any information on how to do it in the [documentation](https://github.com/mailgun/mailgun-php/tree/master/doc).

Could you provide me with an example?

**Comment by DavidGarciaCat** [comment] 2019-05-26 13:17
Hi @wujekbogdan

Given Mailgun SDK uses HTTPlug, then you could use any of the following clients/adapters: http://docs.php-http.org/en/latest/clients.html

I personally like Buzz because is a very light HTTP Client but this is more up to you.

Please note that if you are getting a network exception with Buzz then you'll probably get it too with any other client.

Cheers,

**Comment by wujekbogdan** [comment] 2019-05-27 09:22
> Given Mailgun SDK uses HTTPlug, then you could use any of the following clients/adapters: http://docs.php-http.org/en/latest/clients.html

Is there anything I need to do in order to wire-up an HTTP adapter after I install it with composer? Mailgun documentation doesn't tell anything about it.

**Comment by DavidGarciaCat** [comment] 2019-05-27 21:06
Hi @wujekbogdan 

Please check the [Installation](https://github.com/mailgun/mailgun-php#installation) section of the Read Me file, where you can see that the Mailgun SDK can be installed with the required dependencies for the HTTPlug:

```
composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7
```

Given this SDK uses HTTPlug, then you can replace the package used for this example (`kriswallsmith/buzz`) and install another one. The following packages provide `psr/http-client-implementation` so any of them will work, please note that Buzz is the 2nd one of the list:

https://packagist.org/providers/psr/http-client-implementation

Cheers,

**Comment by wujekbogdan** [comment] 2019-06-05 06:49
@DavidGarciaCat 
So, in order to use Guzzle I have to do:

```
composer require mailgun/mailgun-php php-http/guzzle6-adapter
```

And I don't need to explicityly "tell" mailgun-php which implementation to use. Mailgun will pick a compatible implementation under the hood. Am I right?

It looks a bit magic, so maybe it would be good to make it more explicit in the documentation? The documentation just says to enter the folliowing command:

```
composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7
```

But it doesn't explain what the `nyholm/psr7` and the `kriswallsmith/buzz` packages are and how Mailgun makes use of it.

**Comment by DavidGarciaCat** [comment] 2019-06-06 18:42
Hi @wujekbogdan 

Correct, all the magic happens automatically thanks to the HTTP Plug and the Auto-Discovery 

Yep, not all the adapters are yet using the latest versions, so some manual adjustments on some cases (not all of them) might be required.

Yep, mMaybe we can add more links to the readme, like another reading for further details.
