### ISSUE TITLE
Puli Factory is not available

### ISSUE THREAD

**Issue by purpletoolz** [mailgun/mailgun-php#665] opened 2020-02-17 15:21 UTC
I've been using the PHP interface for Mailgun for ages but today it threw the following during Mailgun::create(<MY_API_KEY>):

Exception has occurred.
Http\Discovery\Exception\PuliUnavailableException: Puli Factory is not available

This is on line 40 of PuliBetaStrategy.php

I updated to the latest version of the repo using 'composer update' but the problem remains?  I'm on the 'concept' (free) plan running PHP v7.2 and debugging PHP via MS Code.  As I say, all has been fine for months until today?

**Comment by Lukakva** [comment] 2020-03-19 11:11
Try running 

``composer require php-http/curl-client guzzlehttp/psr7 php-http/message``

**Comment by bernardo-martinez** [comment] 2020-08-16 09:12
have you solved the issue? I got a lot of version conflicts when trying `composer require php-http/curl-client guzzlehttp/psr7 php-http/message`

**Comment by DavidGarciaCat** [comment] 2020-08-16 09:55
Can you please try with this set of vendors, just to discard other problems?

```
composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7
```

**Comment by olivertappin** [comment] 2020-09-01 11:29
I also came across this issue. When following [Mailgun's installation instructions](https://documentation.mailgun.com/en/latest/libraries.html#php), I experienced the following:

```
<br />
<b>Fatal error</b>:  Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors
 - Puli Factory is not available
 - No valid candidate found using strategy &quot;Http\Discovery\Strategy\CommonClassesStrategy&quot;. We tested the following candidates: .
 - No valid candidate found using strategy &quot;Http\Discovery\Strategy\CommonPsr17ClassesStrategy&quot;. We tested the following candidates: Nyholm\Psr7\Factory\Psr17Factory, Zend\Diactoros\UriFactory, GuzzleHttp\Psr7\HttpFactory, Http\Factory\Diactoros\UriFactory, Http\Factory\Guzzle\UriFactory, Http\Factory\Slim\UriFactory, Laminas\Diactoros\UriFactory.

 in /Users/oliver/Sites/app/vendor/php-http/discovery/src/Exception/DiscoveryFailedException.php:41
Stack trace:
#0 /Users/oliver/Sites/app/vendor/php-http/discovery/src/ClassDiscovery.php(79): Http\Discovery\Exception\DiscoveryFailedException::create(Array)
#1 /Users/oliver/Sites/app in <b>/Users/oliver/Sites/app/vendor/php-http/discovery/src/Psr17FactoryDiscovery.php</b> on line <b>22</b><br />
```

I can confirm that removing the unnecessary dependencies and instead, using the requirements defined by this repositories [README.md](https://github.com/mailgun/mailgun-php#installation):

```
composer remove php-http/guzzle6-adapter php-http/message
composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7
```

For those installing for the first time, the composer command would be as the [README.md](https://github.com/mailgun/mailgun-php#installation) file states (as well as the [comment](https://github.com/mailgun/mailgun-php/issues/665#issuecomment-674506254) above):

```
composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7
```

Is correct, and now works as expected.

I suspect this issue has been raised due to a change in the handlers, and the old documentation is still discoverable, and now out of date. If someone is able to have the [Mailgun website](https://documentation.mailgun.com/en/latest/libraries.html#php) changed to show the latest installation instructions, that should be enough to address this issue and close it.

**Comment by DavidGarciaCat** [comment] 2020-09-25 18:08
Closing this issue as it seems to be resolved when installing the Mailgun SDK + the suggested packages (or other HttPlug and PSR7 implementations).

**Closed by DavidGarciaCat** 2020-09-25 18:08 UTC

**Comment by temuri416** [comment] 2020-10-31 18:37
It does not look like it's been resolved. Followed above steps and getting the same error.

**Comment by temuri416** [comment] 2020-10-31 19:33
@olivertappin 

Creating `composer.json` like:

```
{
    "require": {
        "mailgun/mailgun-php": "^3.0",
        "kriswallsmith/buzz": "^1.1",
        "nyholm/psr7": "^1.3"
    }
}
```
and running `composer install` does not fix the `Puli Factory is not available` error.

what am I missing?

**Comment by DavidGarciaCat** [comment] 2020-11-16 17:11
Hi, @temuri416 

Without more info, hard to say - I can see any error following these steps.

Do you have any other dependency on your project that might be conflicting with the SDK?

----

I have just pulled a Docker PHP image and got access to the bash:

```
docker run -it php:7.4-fpm bash
```

Then I ran the commands to install Composer

```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php --install-dir=/usr/local/bin --filename=composer
composer --version
rm composer-setup.php 
```

After that, installed the PHP ZIP extension (required when unpacking composer packages)

```
apt update
apt-get install -y zip unzip zlib1g-dev libzip-dev
docker-php-ext-install zip
```

And finally installed the dependencies

```
root@e0d82a7fc401:/var/www/html# composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7
Using version ^3.1 for mailgun/mailgun-php
Using version ^1.1 for kriswallsmith/buzz
Using version ^1.3 for nyholm/psr7
./composer.json has been created
Running composer update mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7
Loading composer repositories with package information
Updating dependencies
Lock file operations: 19 installs, 0 updates, 0 removals
  - Locking clue/stream-filter (v1.5.0)
  - Locking kriswallsmith/buzz (1.1.0)
  - Locking mailgun/mailgun-php (3.1.0)
  - Locking nyholm/psr7 (1.3.2)
  - Locking php-http/client-common (2.3.0)
  - Locking php-http/discovery (1.12.0)
  - Locking php-http/httplug (2.2.0)
  - Locking php-http/message (1.10.0)
  - Locking php-http/message-factory (v1.0.2)
  - Locking php-http/multipart-stream-builder (1.1.2)
  - Locking php-http/promise (1.1.0)
  - Locking psr/http-client (1.0.1)
  - Locking psr/http-factory (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking symfony/deprecation-contracts (v2.2.0)
  - Locking symfony/options-resolver (v5.1.8)
  - Locking symfony/polyfill-ctype (v1.20.0)
  - Locking symfony/polyfill-php80 (v1.20.0)
  - Locking webmozart/assert (1.9.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 19 installs, 0 updates, 0 removals
  - Downloading symfony/polyfill-php80 (v1.20.0)
  - Downloading symfony/deprecation-contracts (v2.2.0)
  - Downloading symfony/options-resolver (v5.1.8)
  - Downloading psr/http-message (1.0.1)
  - Downloading psr/http-factory (1.0.1)
  - Downloading psr/http-client (1.0.1)
  - Downloading php-http/promise (1.1.0)
  - Downloading php-http/httplug (2.2.0)
  - Downloading kriswallsmith/buzz (1.1.0)
  - Downloading symfony/polyfill-ctype (v1.20.0)
  - Downloading webmozart/assert (1.9.1)
  - Downloading php-http/message-factory (v1.0.2)
  - Downloading php-http/discovery (1.12.0)
  - Downloading php-http/multipart-stream-builder (1.1.2)
  - Downloading clue/stream-filter (v1.5.0)
  - Downloading php-http/message (1.10.0)
  - Downloading php-http/client-common (2.3.0)
  - Downloading mailgun/mailgun-php (3.1.0)
  - Downloading nyholm/psr7 (1.3.2)
  - Installing symfony/polyfill-php80 (v1.20.0): Extracting archive
  - Installing symfony/deprecation-contracts (v2.2.0): Extracting archive
  - Installing symfony/options-resolver (v5.1.8): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing php-http/promise (1.1.0): Extracting archive
  - Installing php-http/httplug (2.2.0): Extracting archive
  - Installing kriswallsmith/buzz (1.1.0): Extracting archive
  - Installing symfony/polyfill-ctype (v1.20.0): Extracting archive
  - Installing webmozart/assert (1.9.1): Extracting archive
  - Installing php-http/message-factory (v1.0.2): Extracting archive
  - Installing php-http/discovery (1.12.0): Extracting archive
  - Installing php-http/multipart-stream-builder (1.1.2): Extracting archive
  - Installing clue/stream-filter (v1.5.0): Extracting archive
  - Installing php-http/message (1.10.0): Extracting archive
  - Installing php-http/client-common (2.3.0): Extracting archive
  - Installing mailgun/mailgun-php (3.1.0): Extracting archive
  - Installing nyholm/psr7 (1.3.2): Extracting archive
9 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
6 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
root@e0d82a7fc401:/var/www/html#
```

**Comment by olivertappin** [comment] 2020-12-08 14:02
The issue is *this* out-of-date documentation: https://documentation.mailgun.com/en/latest/libraries.html#php

**Comment by DavidGarciaCat** [comment] 2020-12-09 13:29
Mailgun Docs is hosted into another repo which I don't have permissions. Some of the docs were updated, yet is better following the install and configuration steps we have in the Readme: https://github.com/mailgun/mailgun-php#installation
