### ISSUE TITLE
New EU region for Mailgun

### ISSUE THREAD

**Issue by clicars** [mailgun/mailgun-php#471] opened 2018-07-27 10:10 UTC
Mailgun has introduced a new EU region. There are two problems:

a) In Mailgun platform when you edit your domain, they notice you that api url is https://api.mailgun.net which is wrong. Correct api endpoint is https://api.eu.mailgun.net
b) Same problem in mailgun-php. By default you use in Mailgun::create method US api endpoint.

At this time for solving this problem I have had to use ::configure instead of ::create in this way:

Mailgun::configure((new HttpClientConfigurator())->setApiKey($key)->setEndpoint('https://api.eu.mailgun.net'));

It is cleaner to use create method. It would be cool if you introduce a second param in create static method to choose your region.

**Comment by DavidGarciaCat** [comment] 2018-07-27 10:15
Hi @clicars 

The new EU service was announced yesterday, and it requires some adjustments to align the SDK with the new available options.

We can take a look as soon as we can, but if you're feeling comfortable, a Pull Request is always welcomed.

Best,

**Comment by ryryan** [comment] 2018-07-28 17:35
Hi,
I stumbled across this issue. @clicars' code didn't work out of the box. So in case anyone has this issue whilst we wait for a full EU support, here's mine.
```
$configurator = new HttpClientConfigurator();
$configurator->setEndpoint('https://api.eu.mailgun.net/v3/'.$domain.'/messages');
$configurator->setDebug(true);
$configurator->setApiKey($key);
$mailgun = Mailgun::configure($configurator);
```

**Comment by pinonirvana** [comment] 2018-10-01 15:17
I tried to use this solution.
it works for sending messages, but not for other tasks.
For instance if I want to retrieve the list of my european domains, the code only retrieves the USA ones.

The code I tried is this:
```
$mgClient = Mailgun::configure((new HttpClientConfigurator())->setApiKey($this->api)->setEndpoint('https://api.eu.mailgun.net'));

 $result = $mgClient->get("domains");      
 print_r($result);
```

**Comment by DavidGarciaCat** [comment] 2018-10-02 23:49
Hi @pinonirvana 

Can you please try with this other call?
```php
$mgClient = Mailgun::create($apiKey, $endpoint = 'https://api.eu.mailgun.net');

$result = $mgClient->get("domains");      
print_r($result);
```

Cheers,

**Comment by martijn103** [comment] 2018-10-10 08:13
Hi @DavidGarciaCat, I'm having the same problem. I'm afraid the code you suggested still returns the US domains.

**Comment by DavidGarciaCat** [comment] 2018-10-10 14:53
Hey @martijn103 

I think I did a mistake setting the 2nd argument,it shouldn't be a variable but just the copy:

```php
$mgClient = Mailgun::create($apiKey, 'https://api.eu.mailgun.net');

$result = $mgClient->get("domains");      
print_r($result);
```

Can you please confirm?

Thanks,

PS: I don't remember if this 2nd argument was released with a new tag; if not, please try setting the `dev-master` branch on your `composer.json` file.

**Comment by DavidGarciaCat** [comment] 2018-10-10 14:55
Hey @martijn103 

You might want to use the new call to retrieve the domains list too:
```php
$domains = $mgClient->domains()->index();
```
Where `index()` has 2 arguments:
- $limit = 100
- $skip = 0

Cheers,

**Comment by DavidGarciaCat** [comment] 2018-10-11 08:28
Glad it worked! I have been discussing with other collaborators the roadmap to release a new version, so we are aiming to provide the new tagged release soon.

Closing this issue because you have confirmed it solved your problem.

Cheers,

**Closed by DavidGarciaCat** 2018-10-11 08:28 UTC

**Comment by paul-adams-985** [comment] 2019-05-08 06:00
Hi there, was this released?

**Comment by DavidGarciaCat** [comment] 2019-05-08 08:39
Hi @paul-adams-985 

Please try using the [v3.0.0 Beta 1](https://github.com/mailgun/mailgun-php/releases/tag/3.0.0-beta1)

Cheers,
