### ISSUE TITLE
Retrieving stored messages

### ISSUE THREAD

**Issue by krystalcode** [mailgun/mailgun-php#168] opened 2016-09-06 05:13 UTC
Hello,

Does this library provide functionality for retrieving stored messages? I can get the url from the 'events' endpoint, but then do I have to use another http library such as curl to get the messages? It would be nice to use the same library for all endpoints.

**Comment by krystalcode** [comment] 2016-09-06 06:17
Here's some code I came up with for getting stored messages via events API, in case anybody else is trying to figure it out. Warning: this is just a test, not production ready.

```
$apiKey = 'your-api-key';
$domain = 'you-domain.com';

$mailgun = new Mailgun($apiKey);
$mailgun->setApiVersion('v3');
$eventsResponse = $mailgun->get("$domain/events", ['event' => 'stored']);
$responseBody = $eventsResponse->http_response_body;

if (!empty($responseBody->items)) {
  foreach ($responseBody->items as $item) {
    $url = $item->storage->url;
    $urlParts = explode('/', $url);

    $protocol    = array_shift($urlParts);
    $nothing     = array_shift($urlParts);
    $apiHost     = array_shift($urlParts);
    $apiVersion  = array_shift($urlParts);
    $endpointUrl = implode('/', $urlParts);

    $mailgun = new Mailgun($apiKey, null, $apiHost);
    $mailgun->setApiVersion($apiVersion);
    $response = $mailgun->get($endpointUrl);
    $responseBody = $response->http_response_body;
  }
}
```

It's a bit tedious though and would need even more boilerplate to scroll through paged results and using time ranges etc., so it would be nice to have the library provide some functionality that helps with all that, including Events API and retrieving individual messages via given urls.

**Comment by Nyholm** [comment] 2016-09-06 11:50
Hey. 
Thank you for this. I believe this should be done in a more easy way.

**Comment by newscloud** [comment] 2016-09-27 05:21
I opened this with Mailgun 23 days ago - theyre working on it ... here's copies of their replies. No word since 9/13.

Hi Jeff,

It looks like the issue here is that when using a GET request with the SDK it assumes the baseURL is going to be api.mailgun.net instead of so.api.mailgun.net or si.api.mailgun.net. 

I'm going to review this with the team to determine if this is the cause and will look into getting the PHP library updated with a fix.

I'll let you know once we have more information.

Thanks,
Chris@MG


Howdy Jeff,

Our apologies. We've been inundated with support request this week. Going to follow up with Chris and get you update. I don't have an ETA at this time to provide unfortunately.

Thanks,
Nolan
@Mailgun


Howdy Jeff,

I'm working with the development team on a best approach to push a fix for this. You already be aware that currenlty the PHP SDK has the base API endpoint set to "api.mailgun.net". (https://github.com/mailgun/mailgun-php/blob/master/src/Mailgun/Mailgun.php#L36-L43) This is utilized by the SDK for all requests. With the changes to the stored event, will need to add some logic to the SDK to handle processing the request for each host. 

Again, I do apologize I can't give an exact ETA. Currently we're discussing best approach. Once we've decided, we'll apply the needed changes and test. During which I can keep you updated and give you an estimated ETA on a resolution.

Happy to answer any questions.

Thanks,
Nolan
@Mailgun

**Comment by Nyholm** [comment] 2016-09-27 05:26
Thank you @newscloud. Keep this thread updates.

**Comment by krystalcode** [comment] 2016-09-28 02:20
A great improvement would be to provide an endpoint for retrieving the messages from multiple urls in one request. Say I am retrieving in a cron job the messages for 1 day, they may be hundreds or thousands of messages. Currently I would have to make a few requests for scrolling the events, and hundreds or thousands of requests for actually retrieving the messages.

Is this feasible to implement?

**Comment by Nyholm** [comment] 2016-09-28 11:38
I like that idea and I believe that is a direction we should investigate more in. I've labeled this issue and some more with a [Better API](https://github.com/mailgun/mailgun-php/milestone/1) milestone.

**Comment by jrodom** [comment] 2016-10-12 22:53
we've just hired a new developer, @pirogoeth who is working on this issue now.

**Comment by pirogoeth** [comment] 2016-10-12 23:01
@Nyholm I'm working on this issue right now -- do you have any ideas on the best way to implement this?

**Comment by Nyholm** [comment] 2016-10-13 04:50
I do only have ideas and thoughts. Maybe we could have a quick call to figure out a proposal for how we solve the "better API" milestone. 
Send me an email och ping me on twitter

**Comment by pirogoeth** [comment] 2016-10-13 19:26
@Nyholm Actually, could you send me an email? We can get a call going tomorrow and figure out a plan of action for the "better API" milestone. You can get me at sean@mailgun.com

**Comment by Nyholm** [comment] 2016-10-13 20:39
I've sent you an email. I'll stick around for a few more minutes. It is getting late here.

**Comment by Nyholm** [comment] 2016-12-07 22:09
I've created a PR #247 that will solve this issue.

**Closed** 2016-12-07 22:29 UTC
Labels: enhancement
